# Generated by Django 5.1.4 on 2025-10-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name_of_father',
            field=models.TextField(default='abc'),
        ),
    ]
