# Generated by Django 4.2.7 on 2025-12-06 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_comment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
