# Generated by Django 5.1.4 on 2025-11-12 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('distributer', '0001_initial'),
        ('genre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=30)),
                ('producer', models.CharField(max_length=30)),
                ('production_company', models.CharField(max_length=30)),
                ('cast', models.CharField(max_length=100)),
                ('story', models.TextField()),
                ('runtime', models.CharField(max_length=30)),
                ('distributer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributer.distributer')),
                ('genre', models.ManyToManyField(to='genre.genre')),
            ],
        ),
    ]
