# Generated by Django 5.1.4 on 2025-11-09 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conetent',
            new_name='content',
        ),
    ]
