# Generated by Django 4.2.7 on 2026-01-06 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_rename_loan_approve_transaction_laon_approve_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='laon_approve',
            new_name='loan_approve',
        ),
    ]
