# Generated by Django 4.2.7 on 2025-12-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
