# Generated by Django 4.2.7 on 2025-11-19 03:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_release_date',
            field=models.DateField(verbose_name=datetime.datetime(2025, 11, 19, 9, 9, 58, 498146)),
        ),
    ]
