# Generated by Django 4.2.7 on 2026-01-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='initial_deposite_date',
            new_name='initial_deposit_date',
        ),
    ]
