# Generated by Django 4.2.7 on 2025-12-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='quantity',
        ),
    ]
