# Generated by Django 4.2.7 on 2025-11-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('date_time_field', models.DateTimeField()),
                ('duration_field', models.DurationField()),
                ('generic_ip_address_field', models.GenericIPAddressField()),
                ('json_field', models.JSONField()),
                ('positive_integer_field', models.PositiveIntegerField()),
                ('slug_field', models.SlugField()),
                ('url_field', models.URLField()),
            ],
        ),
    ]
