# Generated by Django 4.2.7 on 2025-11-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Enter your first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Enter your last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Enter your email')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number (Optinal)')),
                ('instrument_type', models.CharField(max_length=50)),
            ],
        ),
    ]
