# Generated by Django 4.2.7 on 2025-11-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Phone number'),
        ),
    ]
