# Generated by Django 4.2.7 on 2026-03-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servise',
            new_name='Service',
        ),
    ]
