# Generated by Django 4.2.7 on 2026-03-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_rename_servise_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Service'},
        ),
    ]
