# Generated by Django 4.2.7 on 2025-11-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50, verbose_name='Task Title')),
                ('task_description', models.TextField(verbose_name='Description')),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assign_date', models.DateField()),
                ('category', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
