# Generated by Django 4.2.7 on 2025-12-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
    ]
